### PR TITLE
Improve legibility of the SPWM waveform in PWMsin_2.png

### PR DESCRIPTION
**Pull request by the-gobleo-tinkerer**
In the original plot it's not immediately obvious which areas are on and which are off, due to the presence of the baseline throughout the entire trace, and the height of the trace (meaning its top and the baseline being far apart and not easy to focus on at the same time). I removed the baseline and replaced it with a shading under the SPWM curve to make the duty cycle more obvious. I would also suggest shrinking the whole graph down to ~1/4 the original height and/or increasing the trace thickness for even better legibility; but I'd like to hear what @Irev-Dev thinks before implementing those.

### CODE REVIEW

**Review by Irev-Dev — APPROVED** [review]

**Comment by Irev-Dev** [comment]
Thanks @shuyuan-liu,

I'll happily merge your other suggestions too.

**Comment by the-gobleo-tinkerer** [comment]
Thanks @Irev-Dev for merging. I'll need some time to make the other changes as it's not easy to thicken the sine curve by hand. Maybe it's easier to generate a new graph completely.  @Terbytes could I ask how you created the plot and if there's any data I could use to plot a new one?

**Comment by Irev-Dev** [comment]
Terbytes is an old github account that I closed btw.

I made it in with matlab, but was a long time ago and have since lost code, sorry.

**Comment by the-gobleo-tinkerer** [comment]
That's ok, I'll see what I can do.

**Pull request merged**
